name: unit-tests
on: [push]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go mod download && go mod verify
      - name: Execute tests
        run: go test ./...
